### ISSUE TITLE
Export attribute in a belongs_to association?

### ISSUE THREAD

**Issue by fernandomm** [beerlington/render_csv#15]
If I have a model like this one:

```
class Comment < ActiveRecord::Base
  belongs_to :article
end
```

Can i add the article name ( or another attribute ) somehow in the generated CSV?

**Comment by luismiv85** [comment]
Hi Fernando!

You have to use "add_methods" method that give you this gem. For example, I want to get all roles from my users. Looks like I made it:

controller:
render csv: @results, only: [:name, :surname, :email, :phone], add_methods: [:rol]

user class:

  def rol
    roles = self.roles.map(&:name)
    arr = []
    roles.each {|r| arr.push(I18n.t "rol.#{r}") }
    arr.join(", ")
  end

**Comment by beerlington** [comment]
@fernandomm sorry for the delay on this. You can use `delegate` in your Comment model:

```ruby
class Comment
  belongs_to :article
  delegate :name, to: :article, prefix: true
end
```

Then in the controller, add `article_name` to the list of columns you want. You'll want to eager load the articles to avoid n+1 queries.

```ruby
render csv: @comments, add_methods: [:article_name]
```

**Comment by beerlington** [comment]
I looked into this a bit and have decided not to continue maintaining this project. I have not used it in production for a few years, and do not recommend that others do so. See https://github.com/beerlington/render_csv/commit/8356d727acefb4d8ba6efa28b725192bc9eafd91

**Comment by beerlington** [comment]
Closing this since I am no longer maintaining it and won't be adding new features.
