### ISSUE TITLE
Change title of columns

### ISSUE THREAD

**Issue by luismiv85** [beerlington/render_csv#16]
First at all, great job!
it is possible to change name columns? I mean, my app is built in spanish but the names of attributes are in english, so when I export datas the name of columns are in english.

Any solution for this!

Thanks a lot!

**Comment by beerlington** [comment]
There's an [open PR](https://github.com/beerlington/render_csv/pull/14) for this that the author hasn't responded to since Feb that I forgot about. I may take the PR over if I don't hear anything back from him soon.

**Comment by beerlington** [comment]
I looked into this a bit and have decided not to continue maintaining this project. I have not used it in production for a few years, and do not recommend that others do so. See https://github.com/beerlington/render_csv/commit/8356d727acefb4d8ba6efa28b725192bc9eafd91

**Comment by beerlington** [comment]
Closing this since I am no longer maintaining it and won't be adding new features.
