### ISSUE TITLE
specifying separator

### ISSUE THREAD

**Issue by quentic** [beerlington/render_csv#9]
Hi,

Your Gem is really useful to me. However, I'm wondering if I could specify the field separator. The default is comma. Could it be semicolumn for example (as I've commas in my data) ?

Thanks
Christian

**Comment by beerlington** [comment]
I have decided not to continue maintaining this project. I have not used it in production for a few years, and do not recommend that others do so. See https://github.com/beerlington/render_csv/commit/8356d727acefb4d8ba6efa28b725192bc9eafd91

**Comment by beerlington** [comment]
Closing this since I am no longer maintaining it and won't be adding new features.
